title: Daniel R Ladd
logo: "C:\Users\DLadd\OneDrive - New England College\Dan\Profile Pic.jpg"
description: Turning data into insights, insights into decisions, and decisions into value. 
show_download: false
remote_theme: pages-themes/minimal@v0.2.0
