title: Daniel R Ladd
description: [Resume](https://github.com/dlagit2quit/Portfolio/blob/50350d46900d1004cc8d093682acd03ed15132f1/docs/resume.md)
logo: docs/Profile Pic.jpg
# show_downloads: true
theme: jekyll-theme-minimal
