title: Daniel R Ladd
description: Open to Work
logo: /Profile Pic 2.jpg
# show_downloads: true
theme: jekyll-theme-minimal
linkedin_username: https://www.linkedin.com/in/dan-ladd-1b4b96154/
header pages:
  - test 1
  - test 2
