title: Daniel R Ladd
description: [Resume](docs/resume.md)
# logo: https://github.com/dlagit2quit/Portfolio/blob/7561c2753e020deea6b0d5d1a3d975b338b16af5/docs/Profile%20Pic.jpg
# show_downloads: true
theme: jekyll-theme-minimal
